{
  "zero_optimization":
    {
      "stage": 3,
      "offload_optimizer": { "device": "none" },
      "contiguous_gradients": true,
      "overlap_comm": true,
    },
  "distributed_type": "ddp",
  "gradient_clipping": "none",
  "train_batch_size": "auto",
  "gradient_accumulation_steps": 8,
  "bf16": { "enabled": true },
  "optimizer":
    {
      "type": "AdamW",
      "params":
        {
          "lr": 2e-5,
          "betas": [0.9, 0.999],
          "eps": 1e-8,
          "weight_decay": 0.01,
        },
    },
}
