version: "3"
services:
  deepseek-test-dg:
    container_name: deepseek-test-container
    image: deepseek-test-image
    runtime: nvidia
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USERNAME: ${USERNAME:-devuser}
        USER_UID: ${UID:-1001}
        USER_GID: ${GID:-1001}
    shm_size: '16gb'  # Increased for ML workloads
    ulimits:
      memlock: -1
      stack: 67108864
    working_dir: /workspace
    tty: true
    volumes:
      - ../deepseek-test-dg:/workspace
      - uv-cache:/home/devuser/.cache/uv
      - /mnt/st1/DeepSeekV3-2:/mymodels
    environment:
      ENV: "dev"
      TZ: "Africa/Nairobi"  # Updated timezone
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
      DEVICE: "gpu"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0','1','2','3','4','5','6','7']  # Updated for 8 GPUs
              capabilities: [gpu]
    command: bash

volumes:
  uv-cache: